/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author ahmme
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        choosewhattoEnterlable = new javax.swing.JLabel();
        StudentOperationscombobox = new javax.swing.JComboBox<>();
        enterdatalable = new javax.swing.JLabel();
        Submitbutton = new javax.swing.JButton();
        txtfieldinput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Add Student...");
        jLabel1.setToolTipText("");

        choosewhattoEnterlable.setBackground(new java.awt.Color(255, 0, 51));
        choosewhattoEnterlable.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        choosewhattoEnterlable.setForeground(new java.awt.Color(255, 0, 0));
        choosewhattoEnterlable.setText("Choose what to insert for new Student:");
        choosewhattoEnterlable.setToolTipText("");

        StudentOperationscombobox.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        StudentOperationscombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student ID", "Full Name", "Age", "Gender", "Department", "GPA" }));
        StudentOperationscombobox.setVerifyInputWhenFocusTarget(false);

        enterdatalable.setBackground(new java.awt.Color(255, 0, 51));
        enterdatalable.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        enterdatalable.setForeground(new java.awt.Color(255, 0, 0));
        enterdatalable.setText("Enter data:");
        enterdatalable.setToolTipText("");

        Submitbutton.setBackground(new java.awt.Color(255, 255, 0));
        Submitbutton.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Submitbutton.setForeground(new java.awt.Color(255, 0, 0));
        Submitbutton.setText("Submit");
        Submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttonActionPerformed(evt);
            }
        });

        txtfieldinput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfieldinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldinputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choosewhattoEnterlable)
                            .addComponent(enterdatalable)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(StudentOperationscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtfieldinput, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(choosewhattoEnterlable)
                .addGap(18, 18, 18)
                .addComponent(StudentOperationscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterdatalable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldinput)
                .addGap(18, 18, 18)
                .addComponent(Submitbutton)
                .addGap(20, 20, 20))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Addstudent lable");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldinputActionPerformed

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed
     String selectedField = StudentOperationscombobox.getSelectedItem().toString();
    String input = txtfieldinput.getText().trim();

    // Step 1: Check for empty input
    if (input.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter a value before submitting!",
                "Input Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Step 2: Validate numeric fields
    if (selectedField.equals("Student ID") || selectedField.equals("Age") || selectedField.equals("GPA")) {
        try {
            Double.parseDouble(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    selectedField + " must be a valid number!",
                    "Input Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    // Step 3: Validate gender
    if (selectedField.equals("Gender")) {
        if (!(input.equalsIgnoreCase("Male") || input.equalsIgnoreCase("Female"))) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Invalid Gender! Please enter 'Male' or 'Female'.",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    // Step 4: Optional unique Student ID check (for future database use)
    if (selectedField.equals("Student ID")) {
        // Example placeholder for later:
        // if (Database.containsStudentID(Integer.parseInt(input))) {
        //     javax.swing.JOptionPane.showMessageDialog(this,
        //             "This Student ID already exists!",
        //             "Duplicate ID",
        //             javax.swing.JOptionPane.ERROR_MESSAGE);
        //     return;
        // }
    }

    // Step 5: Show success message
    javax.swing.JOptionPane.showMessageDialog(this,
            selectedField + " added successfully!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SubmitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> StudentOperationscombobox;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JLabel choosewhattoEnterlable;
    private javax.swing.JLabel enterdatalable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtfieldinput;
    // End of variables declaration//GEN-END:variables
}
