package gui;

import backend.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Comparator;

public class DeleteStudents extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private StudentDB db;

    public DeleteStudents() throws FileNotFoundException {
        initComponents();
        db = new StudentDB("data/students"); // path to your student file
        try {
            db.readFromFile(); // load existing students
        } catch (Exception e) {
            System.out.println("File not found or empty: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeleteStudentsTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAscending = new javax.swing.JButton();
        btnDescending = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Delete Students");

        DeleteStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Student ID", "Full Name", "Age", "Gender", "Department", "GPA"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        DeleteStudentsTable.setShowGrid(true);
        DeleteStudentsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DeleteStudentsTable);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAscending.setText("Ascending");
        btnAscending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscendingActionPerformed(evt);
            }
        });

        btnDescending.setText("Descending");
        btnDescending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescendingActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Sort by GPA");

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Selection");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnAscending)
                                                .addGap(29, 29, 29)
                                                .addComponent(btnDescending)
                                                .addGap(97, 97, 97)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                                .addComponent(btnBack)))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(356, 356, 356))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAscending)
                                        .addComponent(btnDescending)
                                        .addComponent(btnBack)
                                        .addComponent(btnDelete))
                                .addContainerGap())
        );

        btnBack.getAccessibleContext().setAccessibleName("back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        int choice = JOptionPane.showConfirmDialog(
                null, // Parent component (null for a default dialog)
                "Are you sure you want to delete this Selection permanently?", // The confirmation message
                "Confirm Deletion", // The title for the dialog box
                JOptionPane.YES_NO_OPTION // The button options to display
        );

        // Process the user's choice
        if (choice == JOptionPane.YES_OPTION) {
            System.out.println("User chose YES. Deleting record...");

            ArrayList<Student> list = db.getRecords();
            int[] idx = DeleteStudentsTable.getSelectedRows();
            DefaultTableModel model = (DefaultTableModel) DeleteStudentsTable.getModel();
            for (int i = idx.length - 1; i >= 0; i--) {
                db.removeStudent(list.get(idx[i])); // delete from backend
                model.removeRow(idx[i]); // remove from table

            }
        } else if (choice == JOptionPane.NO_OPTION) {
            System.out.println("User chose NO.");
        } else if (choice == JOptionPane.CLOSED_OPTION) {
            System.out.println("User closed the dialog without selecting a button.");
        }

    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ArrayList<Student> list = db.getRecords();
        list.sort(Comparator.comparing(Student::getId));
        try {
            db.writeInFile();
        } catch (Exception e) {
            System.out.println("Error writing to file: " + e.getMessage());
        }
        System.out.println("changes saved to file");
        System.out.println("Going back to Home Screen");
        Home homeframe =  new Home();
        homeframe.setVisible(true);
        homeframe.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAscendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscendingActionPerformed
        // Sorting by an attribute using method references for clarity
        ArrayList<Student> list = db.getRecords();
        list.sort(Comparator.comparing(Student::getGPA));
        DefaultTableModel model = (DefaultTableModel) DeleteStudentsTable.getModel();
        int rowCount = model.getRowCount();
        // Loop backward to safely remove all rows
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{list.get(i).getId(), list.get(i).getFullName(), list.get(i).getAge(), list.get(i).getGender(), list.get(i).getDepartment(), list.get(i).getGPA()});
        }
    }//GEN-LAST:event_btnAscendingActionPerformed

    private void btnDescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescendingActionPerformed
        ArrayList<Student> list = db.getRecords();
        list.sort(Comparator.comparing(Student::getGPA).reversed());
        DefaultTableModel model = (DefaultTableModel) DeleteStudentsTable.getModel();
        int rowCount = model.getRowCount();
        // Loop backward to safely remove all rows
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{list.get(i).getId(), list.get(i).getFullName(), list.get(i).getAge(), list.get(i).getGender(), list.get(i).getDepartment(), list.get(i).getGPA()});
        }
    }//GEN-LAST:event_btnDescendingActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<Student> st = db.getRecords();
        DefaultTableModel model = (DefaultTableModel) DeleteStudentsTable.getModel();
        for (int i = 0; i < st.size(); i++) {
            model.addRow(new Object[]{st.get(i).getId(), st.get(i).getFullName(), st.get(i).getAge(), st.get(i).getGender(), st.get(i).getDepartment(), st.get(i).getGPA()});
        }
        //model.addRow(new Object[]{3 ,"mona" ,3});
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    DeleteStudents frame = new DeleteStudents();
                    frame.setVisible(true);
                    frame.setLocationRelativeTo(null);
                    frame.setDefaultCloseOperation(DeleteStudents.EXIT_ON_CLOSE);
                } catch (FileNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DeleteStudentsTable;
    private javax.swing.JButton btnAscending;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDescending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
